sonar.projectKey=edgewater_fixdecoder
sonar.organization=edgewater
sonar.host.url=https://sonarcloud.io

sonar.language=go
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=*_test.go

sonar.junit.reportPaths=reports/*.xml
sonar.go.coverage.reportPaths=reports/*.out
