sonar.projectKey=edgewater_fixdecoder
sonar.organization=edgewater
sonar.host.url=https://sonarcloud.io

sonar.language=go
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=*_test.go

sonar.junit.reportPaths=test_report.xml
sonar.go.coverage.reportPaths=coverage.out,coverage.integration.out
