// Code generated by fixdecoder from QuickFIX XML specs. DO NOT EDIT.
//
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2026 Steve Clarke stephenlclarke@mac.com - https://xyzzy.tools
//
// This file is generated from FIX protocol XML specifications published by the
// QuickFIX project: https://github.com/quickfix/quickfix/tree/master/spec
// The QuickFIX specifications are licensed under the BSD 2-Clause License.
// Copyright (c) 2001-2015 QuickFIX. All rights reserved.
//
// The full BSD 2-Clause notice for the QuickFIX materials is included in this
// repository’s NOTICE file. This generated file is part of fixdecoder (AGPL-3.0).

//! Automatically generated by `cargo run --bin generate_sensitive_tags`
use once_cell::sync::Lazy;
use std::collections::BTreeMap;

#[rustfmt::skip]
pub static SENSITIVE_TAG_NAMES: Lazy<BTreeMap<u32, &'static str>> = Lazy::new(|| {
let mut map = BTreeMap::new();
    map.insert(1, "Account");
    map.insert(49, "SenderCompID");
    map.insert(50, "SenderSubID");
    map.insert(56, "TargetCompID");
    map.insert(57, "TargetSubID");
    map.insert(79, "AllocAccount");
    map.insert(115, "OnBehalfOfCompID");
    map.insert(116, "OnBehalfOfSubID");
    map.insert(128, "DeliverToCompID");
    map.insert(129, "DeliverToSubID");
    map.insert(142, "SenderLocationID");
    map.insert(143, "TargetLocationID");
    map.insert(144, "OnBehalfOfLocationID");
    map.insert(145, "DeliverToLocationID");
    map.insert(283, "LocationID");
    map.insert(440, "ClearingAccount");
    map.insert(523, "PartySubID");
    map.insert(545, "NestedPartySubID");
    map.insert(553, "Username");
    map.insert(554, "Password");
    map.insert(581, "AccountType");
    map.insert(625, "TradingSessionSubID");
    map.insert(628, "HopCompID");
    map.insert(671, "LegAllocAccount");
    map.insert(717, "SettlSessSubID");
    map.insert(760, "Nested2PartySubID");
    map.insert(785, "SettlPartySubID");
    map.insert(786, "SettlPartySubIDType");
    map.insert(798, "AllocAccountType");
    map.insert(801, "NoSettlPartySubIDs");
    map.insert(802, "NoPartySubIDs");
    map.insert(803, "PartySubIDType");
    map.insert(804, "NoNestedPartySubIDs");
    map.insert(805, "NestedPartySubIDType");
    map.insert(806, "NoNested2PartySubIDs");
    map.insert(807, "Nested2PartySubIDType");
    map.insert(809, "NoUsernames");
    map.insert(823, "UnderlyingTradingSessionSubID");
    map.insert(925, "NewPassword");
    map.insert(930, "RefCompID");
    map.insert(931, "RefSubID");
    map.insert(936, "NoCompIDs");
    map.insert(952, "NoNested3PartySubIDs");
    map.insert(953, "Nested3PartySubID");
    map.insert(954, "Nested3PartySubIDType");
    map.insert(1052, "NoInstrumentPartySubIDs");
    map.insert(1053, "InstrumentPartySubID");
    map.insert(1054, "InstrumentPartySubIDType");
    map.insert(1062, "NoUndlyInstrumentPartySubIDs");
    map.insert(1063, "UndlyInstrumentPartySubID");
    map.insert(1064, "UndlyInstrumentPartySubIDType");
    map.insert(1114, "TriggerTradingSessionSubID");
    map.insert(1120, "NoRootPartySubIDs");
    map.insert(1121, "RootPartySubID");
    map.insert(1122, "RootPartySubIDType");
    map.insert(1296, "NoDerivativeInstrumentPartySubIDs");
    map.insert(1297, "DerivativeInstrumentPartySubID");
    map.insert(1298, "DerivativeInstrumentPartySubIDType");
    map.insert(1400, "EncryptedPasswordMethod");
    map.insert(1401, "EncryptedPasswordLen");
    map.insert(1402, "EncryptedPassword");
    map.insert(1403, "EncryptedNewPasswordLen");
    map.insert(1404, "EncryptedNewPassword");
    map.insert(1411, "Nested4PartySubIDType");
    map.insert(1412, "Nested4PartySubID");
    map.insert(1413, "NoNested4PartySubIDs");
    map.insert(1519, "NoPartyDetailAltSubIDs");
    map.insert(1520, "PartyDetailAltSubID");
    map.insert(1521, "PartyDetailAltSubIDType");
    map.insert(1566, "NoRelatedPartyDetailSubIDs");
    map.insert(1567, "RelatedPartyDetailSubID");
    map.insert(1568, "RelatedPartyDetailSubIDType");
    map.insert(1572, "NoRelatedPartyDetailAltSubIDs");
    map.insert(1573, "RelatedPartyDetailAltSubID");
    map.insert(1574, "RelatedPartyDetailAltSubIDType");
    map.insert(1661, "NoRequestingPartySubIDs");
    map.insert(1662, "RequestingPartySubID");
    map.insert(1663, "RequestingPartySubIDType");
    map.insert(1694, "NoPartyDetailSubIDs");
    map.insert(1695, "PartyDetailSubID");
    map.insert(1696, "PartyDetailSubIDType");
    map.insert(1699, "AccountSummaryReportID");
    map.insert(1816, "ClearingAccountType");
    map.insert(1817, "LegClearingAccountType");
    map.insert(1891, "TrdMatchSubID");
    map.insert(1918, "NoClearingAccountTypes");
    map.insert(2258, "NoLegInstrumentPartySubIDs");
    map.insert(2259, "LegInstrumentPartySubID");
    map.insert(2260, "LegInstrumentPartySubIDType");
    map.insert(2433, "NoTargetPartySubIDs");
    map.insert(2434, "TargetPartySubID");
    map.insert(2435, "TargetPartySubIDType");
    map.insert(2567, "PrimaryServiceLocationID");
    map.insert(2568, "SecondaryServiceLocationID");
    map.insert(2674, "FillMatchSubID");
    map.insert(2680, "LegAccount");
    map.insert(2816, "PostTradePaymentAccount");
    map.insert(40178, "NoProvisionPartySubIDs");
    map.insert(40179, "ProvisionPartySubID");
    map.insert(40180, "ProvisionPartySubIDType");
    map.insert(40238, "NoPaymentSettlPartySubIDs");
    map.insert(40239, "PaymentSettlPartySubID");
    map.insert(40240, "PaymentSettlPartySubIDType");
    map.insert(40537, "NoLegProvisionPartySubIDs");
    map.insert(40538, "LegProvisionPartySubID");
    map.insert(40539, "LegProvisionPartySubIDType");
    map.insert(42177, "NoUnderlyingProvisionPartySubIDs");
    map.insert(42178, "UnderlyingProvisionPartySubID");
    map.insert(42179, "UnderlyingProvisionPartySubIDType");
    map
});
