#!/usr/bin/env bash
#
# generate_fix_xml_go.sh
# 1) Downloads FIX XML schemas (FIX40, 41, 42, 43, 44, 50) into ./resources
# 2) Generates per-version Go source files embedding the raw XML as a raw string literal.
#
# Usage:
#   ./generate_fix_xml_go.sh
#
set -euo pipefail
IFS=$'\n\t'

URL_BASE="https://raw.githubusercontent.com/quickfix/quickfix/master/spec"
VERSIONS=("40" "41" "42" "43" "44" "50" "50SP1" "50SP2" "T11")

# Create resources directory for XML files
mkdir -p resources

# Step 1: download all XML files into resources/
for ver in "${VERSIONS[@]}"; do
    XML_URL="${URL_BASE}/FIX${ver}.xml"
    DEST="resources/FIX${ver}.xml"

    echo "Downloading ${XML_URL} → ${DEST}..."
    if ! curl -sSf "${XML_URL}" -o "${DEST}"; then
        echo "Error: failed to download ${XML_URL}" >&2
        exit 1
    fi
done

# Step 2: process each downloaded XML into a Go source package
for ver in "${VERSIONS[@]}"; do
    XML_PATH="resources/FIX${ver}.xml"
    PKG="fix${ver}"
    OUT_DIR="${PKG}"
    OUT_FILE="${OUT_DIR}/${PKG}.go"

    echo "Processing ${XML_PATH} → ${OUT_FILE}..."

    # Read and escape backticks so the XML can live in a Go raw string
    escaped_xml=$(awk '{ gsub(/`/, "`\"+\"`\"+`"); print }' "${XML_PATH}")

    # Ensure output directory exists
    mkdir -p "${OUT_DIR}"

    # Write the Go source
    cat > "${OUT_FILE}" <<EOF
// Code generated by generate_fix_xml_go.sh; DO NOT EDIT.
package ${PKG}

// FIX${ver}XML contains the raw FIX ${ver}.0 XML schema.
var FIX${ver}XML = \`
${escaped_xml}
\`
EOF

    echo "  Wrote ${OUT_FILE}"
done

echo "All FIX schemas processed."

