// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2026 Steve Clarke <stephenlclarke@mac.com> - https://xyzzy.tools
//
/// fixdecoder command-line entry point and CLI orchestration.
///
/// The binary ties together the dictionary tooling and the streaming FIX log
/// prettifier.  This file is intentionally light on protocol logic; it wires
/// user input into the focused modules under `src/decoder` and `src/fix`.
/// The comments favour UK English and aim to give future maintainers a quick
/// reminder of why each function exists and how it cooperates with the rest
/// of the app.

// Code generated by generate_fix_go.sh; DO NOT EDIT.
package fix

import (
    fix40    "bitbucket.org/edgewater/fixdecoder/fix/fix40"
    fix41    "bitbucket.org/edgewater/fixdecoder/fix/fix41"
    fix42    "bitbucket.org/edgewater/fixdecoder/fix/fix42"
    fix43    "bitbucket.org/edgewater/fixdecoder/fix/fix43"
    fix44    "bitbucket.org/edgewater/fixdecoder/fix/fix44"
    fix50    "bitbucket.org/edgewater/fixdecoder/fix/fix50"
    fix50SP1 "bitbucket.org/edgewater/fixdecoder/fix/fix50SP1"
    fix50SP2 "bitbucket.org/edgewater/fixdecoder/fix/fix50SP2"
    fixT11   "bitbucket.org/edgewater/fixdecoder/fix/fixT11"
)

// chooseEmbeddedXML returns the raw XML constant for a given FIX version.
func ChooseEmbeddedXML(ver string) string {
    switch ver {
    case "40":
        return fix40.FIX40XML
    case "41":
        return fix41.FIX41XML
    case "42":
        return fix42.FIX42XML
    case "43":
        return fix43.FIX43XML
    case "44":
        return fix44.FIX44XML
    case "50":
        return fix50.FIX50XML
    case "50SP1":
        return fix50SP1.FIX50SP1XML
    case "50SP2":
        return fix50SP2.FIX50SP2XML
    case "T11":
        return fixT11.FIXT11XML
    default:
        // fallback to 44
        return fix44.FIX44XML
    }
}

// supportedFixVersions returns a comma-separated list of supported FIX versions.
func SupportedFixVersions() string {
    return "40,41,42,43,44,50,50SP1,50SP2,T11"
}
