// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2026 Steve Clarke <stephenlclarke@mac.com> - https://xyzzy.tools
//
/// fixdecoder command-line entry point and CLI orchestration.
///
/// The binary ties together the dictionary tooling and the streaming FIX log
/// prettifier.  This file is intentionally light on protocol logic; it wires
/// user input into the focused modules under `src/decoder` and `src/fix`.
/// The comments favour UK English and aim to give future maintainers a quick
/// reminder of why each function exists and how it cooperates with the rest
/// of the app.

// Code generated by generate_fix_go.sh; DO NOT EDIT.
package fix50SP1

import "testing"

func TestFIX50SP1XMLNotEmpty(t *testing.T) {
	if len(FIX50SP1XML) == 0 {
		t.Fatalf("FIX50SP1XML is empty")
	}
}
