// Code generated by generate_fix_go.sh; DO NOT EDIT.
package fix50SP1

import "testing"

func TestFIX50SP1XMLNotEmpty(t *testing.T) {
	if len(FIX50SP1XML) == 0 {
		t.Fatalf("FIX50SP1XML is empty")
	}
}
