// Code generated by generate_fix_go.sh; DO NOT EDIT.
package fix50SP2

import "testing"

func TestFIX50SP2XMLNotEmpty(t *testing.T) {
	if len(FIX50SP2XML) == 0 {
		t.Fatalf("FIX50SP2XML is empty")
	}
}
